In [ ]:
# numpy basic operations

In [1]:
import numpy as np

In [3]:
# ndim returns number of dimensions of array
arr = np.array([10,12,9])
arr.ndim

1

In [7]:
# create two dimension array and ndim function return 2 which means it is two dimention array

cost_array = np.array([[10,12,9],[15,11,13]])
cost_array.ndim

2

In [ ]:
# How to access element 15  (2nd row and 1st column - in python index value starts from 0)
cost_array[1,0]

np.int64(15)

In [9]:
# We can change the value of 15 to 25
cost_array[1,0] = 25
cost_array

array([[10, 12,  9],
       [25, 11, 13]])

In [10]:
# print data type
cost_array.dtype

dtype('int64')

In [14]:
cost_array.nbytes

48

In [12]:
# We can specify the data type float 64 
new_cost_array = np.array([[10,12,9],[15,11,13]], dtype=np.float64)
new_cost_array.dtype

dtype('float64')

In [13]:
new_cost_array.nbytes

48

In [ ]:
# both arrays occupied same space, but flot allows to save flot values.

In [15]:
# We can use itemsize method to know how much memory occupied for each element
new_cost_array.itemsize

8

In [16]:
# how to find number elements - we can use size 
new_cost_array.size

6

In [ ]:
# shape function returns number of rows and columns 
new_cost_array.shape

(2, 3)

In [ ]:
# We can sort the array and doesn't impact on the original array
sorted_array = np.sort(new_cost_array,axis=None)
sorted_array

array([[ 9., 10., 12.],
       [11., 13., 15.]])

In [21]:
# We can generate zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# We can generates onces array
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# We want to create a array between 20 to 30 and include even number (last parameter is step )
np.arange(20,30,2)

array([20, 22, 24, 26, 28])