In [ ]:
# numpy basic operations

In [1]:
import numpy as np

In [3]:
# ndim returns number of dimensions of array
arr = np.array([10,12,9])
arr.ndim

1

In [7]:
# create two dimension array and ndim function return 2 which means it is two dimention array

cost_array = np.array([[10,12,9],[15,11,13]])
cost_array.ndim

2

In [ ]:
# How to access element 15  (2nd row and 1st column - in python index value starts from 0)
cost_array[1,0]

np.int64(15)

In [9]:
# We can change the value of 15 to 25
cost_array[1,0] = 25
cost_array

array([[10, 12,  9],
       [25, 11, 13]])

In [10]:
# print data type
cost_array.dtype

dtype('int64')

In [14]:
cost_array.nbytes

48

In [12]:
# We can specify the data type float 64 
new_cost_array = np.array([[10,12,9],[15,11,13]], dtype=np.float64)
new_cost_array.dtype

dtype('float64')

In [13]:
new_cost_array.nbytes

48

In [ ]:
# both arrays occupied same space, but flot allows to save flot values.

In [15]:
# We can use itemsize method to know how much memory occupied for each element
new_cost_array.itemsize

8

In [16]:
# how to find number elements - we can use size 
new_cost_array.size

6

In [ ]:
# shape function returns number of rows and columns 
new_cost_array.shape

(2, 3)

In [ ]:
# We can sort the array and doesn't impact on the original array
sorted_array = np.sort(new_cost_array,axis=None)
sorted_array

array([[ 9., 10., 12.],
       [11., 13., 15.]])

In [21]:
# We can generate zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# We can generates onces array
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# We want to create a array between 20 to 30 and include even number (last parameter is step )
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [3]:
rev_q = np.array([10,12,9])
rev_q.ndim

1

In [5]:
rev = np.array([[10,12,9],[15,11,13]])
rev.ndim

2

In [6]:
rev

array([[10, 12,  9],
       [15, 11, 13]])

In [7]:
# to access the element in the array - row by column
rev[1,0]

np.int64(15)

In [8]:
rev[1,0] = 14

In [9]:
rev.dtype

dtype('int64')

In [12]:
# We can specify the data type at the creation time
rev = np.array([[10,12,9],[15,11,13]], dtype=np.float64)
rev.dtype

dtype('float64')

In [13]:
rev.itemsize

8

In [14]:
rev.size

6

In [15]:
rev.shape

(2, 3)

In [16]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [17]:
# We can sort the array
np.sort(rev)

array([[ 9., 10., 12.],
       [11., 13., 15.]])

In [18]:
# We can create single dimensions
np.sort(rev, axis=None)

array([ 9., 10., 11., 12., 13., 15.])

In [19]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.arange(20,30,2)  # step function at the last input

array([20, 22, 24, 26, 28])

In [22]:
# If you want to create 20 elements between 10 and 20
np.linspace(10,20,20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [23]:
# Flatten creates new Array and creates single dimension array
rev.flatten()

array([10., 12.,  9., 15., 11., 13.])

In [24]:
# Reshape the array with 3,2 (3 rows and 2 columns)
rev.reshape(3,2)

array([[10., 12.],
       [ 9., 15.],
       [11., 13.]])

In [25]:
rev.min()

np.float64(9.0)

In [26]:
rev.max()

np.float64(15.0)

In [ ]:
rev.sum(axis=1)  # axis 1 means row level and axis 0 means column level

array([31., 39.])

In [28]:
rev.sum(axis=0)

array([25., 23., 22.])

In [29]:
b = np.array([1,4,16])


In [30]:
np.std(b)

np.float64(6.48074069840786)

In [31]:
for row in rev:
    print("row: ->", row)

row: -> [10. 12.  9.]
row: -> [15. 11. 13.]
