In [19]:
# numpy Matrix operations

In [20]:
import numpy as np

In [21]:
q1 = np.array([[200,220,250], # Product A
              [150,180,210], # Product B
              [300,330,360]]) # Product C

q2 = np.array([[209,231,259],  # Product A
              [155,192,222],  # Product B
              [310,340,375]])  # Product C

In [23]:
q1 + q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [24]:
# Sales Growth
q2 - q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [25]:
# % increase
(q2-q1)*100/q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [8]:
price = np.array([[10,12,11],
                  [8,9,10],
                  [15,16,17]])

In [9]:
q1_revenue = q1 * price

In [10]:
q1_revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [11]:
q1_discounts = q1_revenue*0.2

In [12]:
q1_discounts

array([[ 400.,  528.,  550.],
       [ 240.,  324.,  420.],
       [ 900., 1056., 1224.]])

In [13]:
net_revenue = q1_revenue - q1_discounts
net_revenue

array([[1600., 2112., 2200.],
       [ 960., 1296., 1680.],
       [3600., 4224., 4896.]])

In [14]:
np.sum(net_revenue)

np.float64(22568.0)

In [15]:
feature = np.array([[2000,3],
                    [1800,2]])

In [16]:
weights = np.array([150,50000])

In [17]:
np.dot(feature,weights)

array([450000, 370000])

In [18]:
np.cross(feature,weights)

/var/folders/1d/w72pys2d2q58j17kf_kg6h300000gr/T/ipykernel_95101/3719931781.py:1: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(feature,weights)


array([99999550, 89999700])